Fix type mismatch pointed out by Boost 1.57 compiler in adjoints_ex3.
adjoints_ex3.C:506:30: error: no viable overloaded '='
system.time_solver =

Also use more terse reset() syntax instead of explicitly constructing UniquePtrs.