Guard tests in node_test.C
These tests require deprecated code, so they must be disabled if
!LIBMESH_ENABLE_DEPRECATED.  For reference, the error messages when
libmesh is configured with --disable-deprecated are:

In file included from ../../tests/geom/../geom/point_test.h:6:0,
                 from ../../tests/geom/node_test.C:9:
../../tests/geom/../geom/../numerics/type_vector_test.h: In instantiation of ‘void TypeVectorTestBase<DerivedClass>::testAssignment() [with DerivedClass = libMesh::Node]’:
../../tests/geom/node_test.C:28:3:   required from here
../../tests/geom/../geom/../numerics/type_vector_test.h:153:18: error: use of deleted function ‘libMesh::Node::Node(const libMesh::Node&)’
     DerivedClass avector = (*m_1_1_1);
                  ^~~~~~~
and

In file included from ../../tests/geom/node_test.C:10:0:
../../tests/geom/../base/dof_object_test.h: In instantiation of ‘void DofObjectTest<DerivedClass>::testSetId() [with DerivedClass = libMesh::Node]’:
../../tests/geom/node_test.C:30:3:   required from here
../../tests/geom/../base/dof_object_test.h:39:15: error: ‘libMesh::DofObject::DofObject(const libMesh::DofObject&)’ is private within this context
     DofObject aobject(*instance);
               ^~~~~~~