Fix missing include issue in exact_error_estimator.h.
When included alone, you apparently can't get away with just forward
declarations of TypeVector and TypeTensor. The error messages I was
getting were along the lines of:

In file included from /Users/petejw/projects/libmesh_git/installed/include/libmesh/exact_error_estimator.h:25:
/Users/petejw/projects/libmesh_git/installed/include/libmesh/function_base.h:136:18: error: implicit instantiation of undefined template 'libMesh::VectorValue<double>'
  virtual Output component(unsigned int i,
                 ^
/Users/petejw/projects/libmesh_git/installed/include/libmesh/function_base.h:77:11: note: in instantiation of member function 'libMesh::FunctionBase<libMesh::VectorValue<double> >::component' requested here
  virtual ~FunctionBase ();
          ^
/opt/moose/llvm-3.9.0/bin/../include/c++/v1/memory:2541:13: note: in instantiation of member function 'libMesh::FunctionBase<libMesh::VectorValue<double> >::~FunctionBase' requested here
            delete __ptr;
            ^
Refs #1593.